apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-volumes-cephfs
  namespace: test-backups
  annotations:
    description: Enqueue PV jsons to be processed
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      activeDeadlineSeconds: 3600
      template:
        spec:
          serviceAccountName: backup-cephfs-job
          initContainers:
          - image: santos171900/backupcephfs:latest
            name:  enqueue-volumes-cephfs
            env:
            # Get Job ID using Downward API to store this information in env
            - name: JOB_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            command: [ "/enqueue_pvs.sh" ]
            volumeMounts:
            - name: jobinfo
              mountPath: /tmp/etc
              readOnly: false
          restartPolicy: Never
          containers:
          - image: santos171900/backupcephfs:latest
            name:  backups-volumes-cephfs
            securityContext:
              privileged: true
              runAsUser: 0
            volumeMounts:
            - name: jobinfo
              mountPath: /tmp/etc
              readOnly: false
            env:
            # env variables we need for restic
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: cephfs-backup-s3-access-key
                  name: cephfs-backup-secrets
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: cephfs-backup-s3-secret-key
                  name: cephfs-backup-secrets
            - name: RESTIC_REPOSITORY
              valueFrom:
                secretKeyRef:
                  key: cephfs-backup-registry-repository
                  name: cephfs-backup-secrets
            - name: RESTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: cephfs-backup-password
                  name: cephfs-backup-secrets
            command: [ "/backup_pvs.sh" ]
          volumes:
          - name: jobinfo
            downwardAPI:
              defaultMode: 420
              items:
              - fieldRef:
                  fieldPath: metadata.labels
                path: job_labels
          restartPolicy: Never
